name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'   # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "awl4114awl"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
